//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Экзаменационная
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dolzhnosti
    {
        public int KeyDolzhnosti { get; set; }
        public string Dolzhnost { get; set; }
        public double Oklad { get; set; }
    }
}
